AWSTemplateFormatVersion: '2010-09-09'
Description: 'image-processor Sample SAM Template for image-processor

  '
Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 3
Resources:
  ProcessFunction:
    Properties:
      CodeUri: s3://ej-ip/8f7158b143a3e80fbf6ddfd3624ebb58
      Events:
        Process:
          Properties:
            BatchSize: 10
            Queue:
              Fn::GetAtt:
              - ProcessQueue
              - Arn
          Type: SQS
      Handler: app.lambdaHandler
    Type: AWS::Serverless::Function
  ProcessInBucket:
    DependsOn:
    - ProcessQueue
    - ProcessQueuePolicy
    Properties:
      NotificationConfiguration:
        QueueConfigurations:
        - Event: s3:ObjectCreated:*
          Queue:
            Fn::GetAtt:
            - ProcessQueue
            - Arn
    Type: AWS::S3::Bucket
  ProcessQueue:
    Type: AWS::SQS::Queue
  ProcessQueuePolicy:
    DependsOn:
    - ProcessQueue
    Properties:
      PolicyDocument:
        Statement:
          Action:
          - sqs:SendMessage
          Condition:
            ArnLike:
              aws:SourceArn: arn:aws:s3:::*
          Effect: Allow
          Principal: '*'
          Resource:
            Fn::GetAtt:
            - ProcessQueue
            - Arn
        Version: 2012-10-17
      Queues:
      - Ref: ProcessQueue
    Type: AWS::SQS::QueuePolicy
Transform: AWS::Serverless-2016-10-31
