AWSTemplateFormatVersion: '2010-09-09'
Description: Sample SAM Template for image-processor
Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 3
Resources:
  ProcessFunction:
    Properties:
      CodeUri: s3://ej-ip/5ee91fee8c0e10c9882190b63ada1d0e
      Events:
        Bucket:
          Properties:
            Bucket:
              Ref: ProcessInBucket
            Events: s3:ObjectCreated:*
          Type: S3
      Handler: app.lambdaHandler
    Type: AWS::Serverless::Function
  ProcessInBucket:
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
