AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for image-processor

Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 3

Resources:

  ProcessInBucket:
    Type: AWS::S3::Bucket

  ProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: process-service/
      Handler: app.lambdaHandler
      Environment:
        Variables:
          TABLE_NAME: !Ref ResultsTable
      Events:
        Bucket:
          Type: S3
          Properties:
            Bucket: !Ref ProcessInBucket
            Events: s3:ObjectCreated:*

  ResultsTable:
    Type: AWS::Serverless::SimpleTable